
productos = [
    {
        'id': '05e0b91e-2baa-11ed-8f5e-ca2d65174065',
        'nombre': 'Helado',
        'tipo': 'Congelados',
        'precio': 60,
        'caducidad': '30/Ago/2022',
        'neto': 1000,
        'produccion': '15/Ago/2022',
        'temperatura': 12,
        'marca':'Holanda',
    },
    {
        'id': 'aa33df2c-2bb5-12ed-8f5e-ca2d65174065',
        'nombre': 'Concha',
        'tipo': 'Panaderia',
        'precio': 10,
        'marca': 'uamart',
        'peso': 70,
        'caducidad': '14/Agosto/2022',
        'tipo_pan': 'Dulce',
        'sabor': 'chocolate',
    },
    {
        'id': '04a0b26e-2vmd-12ad-3f4s-c22d35144065',
        'nombre': 'Laptop',
        'tipo': 'Electronicos',
        'precio': 18000,
        'marca': 'Apple',
        'utilidad':'Computacion',
        'peso':1200,
    },
    {
        'id': '27e0b91w-2bse-32sf-8f5e-ca2d65174065',
        'nombre': 'Ibuprofeno',
        'tipo': 'Farmacia',
        'precio': 62,
        'gramaje':100,
        'dosis':2,
        'enfermedad':'dolor',
        'tipo_medicamento':'general',
        'controlado':'no'
    },
    {
        'id': '03dda0d4-2f27-11ed-8d4e-542696db244b',
        'nombre': 'Rompecabezas',
        'tipo': 'Juguetes',
        'precio': 1000,
        'marca':'Puzzles',
        'color':'indefinido',
        'tamaño':100,
        'material':'carton',
        'peso':400,
    },
    {
        'id': 'c9cc6eec-2f27-11ed-a909-542696db244b',
        'nombre': 'Suavitel',
        'tipo': 'Limpieza',
        'precio': 40,
        'tamaño':20,
        'marca':'Suavitel',
        'presentacion':'liquida',
        'seccion':'ropa',
        'tipo':'jabon',
        'tipo de jabon':'ropa',
    },
    {
        'id': 'e061747c-2f27-11ed-a909-542696db244b',
        'nombre': 'Shampoo',
        'tipo': 'Mascotas',
        'precio': 32,
        'categoria':'limpieza',
        'especie':'perro',
        'edad':1,
        'raza':'cualquiera',
        'mantenimiento':'lugar fresco',
    },
]
